// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models
{
    public partial class choice
    {
        public int choice_ID { get; set; }
        public string choice_desc { get; set; }
        public string isCorrect { get; set; }
        public int q_ID { get; set; }

        public virtual question q_IDNavigation { get; set; }
    }
}