// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class choices_selectResult
    {
        public int choice_ID { get; set; }
        public string choice_desc { get; set; }
        public string isCorrect { get; set; }
        public int q_ID { get; set; }
    }
}
