// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class courses_selectResult
    {
        public int c_ID { get; set; }
        public string c_name { get; set; }
    }
}
