// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class Department_SelectResult
    {
        public int dept_ID { get; set; }
        public string dept_name { get; set; }
        public int manager_ID { get; set; }
    }
}
