// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models
{
    public partial class department
    {
        public department()
        {
            students = new HashSet<student>();
        }

        public int dept_ID { get; set; }
        public string dept_name { get; set; }
        public int manager_ID { get; set; }

        public virtual instructor manager { get; set; }
        public virtual ICollection<student> students { get; set; }
    }
}