// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models
{
    public partial class exam
    {
        public exam()
        {
            exams_questions = new HashSet<exams_question>();
        }

        public int exam_ID { get; set; }
        public int course_ID { get; set; }

        public virtual course course { get; set; }
        public virtual ICollection<exams_question> exams_questions { get; set; }
    }
}