// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class exams_qu_selectResult
    {
        public int exam_ID { get; set; }
        public int q_ID { get; set; }
        public int? answer { get; set; }
        public int St_ID { get; set; }
    }
}
