// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models
{
    public partial class Exam_Student
    {
        public int St_ID { get; set; }
        public int Exam_ID { get; set; }
        public int? st_grade { get; set; }

        public virtual exam Exam { get; set; }
        public virtual student St { get; set; }
    }
}