// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models
{
    public partial class exams_question
    {
        public int exam_ID { get; set; }
        public int q_ID { get; set; }
        public string answer { get; set; }

        public virtual exam exam { get; set; }
        public virtual question q_IDNavigation { get; set; }
    }
}