// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class finalResultResult
    {
        public int Exam_ID { get; set; }
        public int? st_grade { get; set; }
    }
}
