// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models
{
    public partial class instructor
    {
        public instructor()
        {
            departments = new HashSet<department>();
            courses = new HashSet<course>();
        }

        public int inst_ID { get; set; }
        public string inst_name { get; set; }
        public string inst_username { get; set; }
        public string inst_pw { get; set; }

        public virtual ICollection<department> departments { get; set; }

        public virtual ICollection<course> courses { get; set; }
    }
}