// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class instructor_selectResult
    {
        public int inst_ID { get; set; }
        public string inst_name { get; set; }
        public string inst_username { get; set; }
        public string inst_pw { get; set; }
    }
}
