// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class Questions_SelectResult
    {
        public int q_ID { get; set; }
        public string q_desc { get; set; }
        public string q_type { get; set; }
        public int c_ID { get; set; }
    }
}
