// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models
{
    public partial class question
    {
        public question()
        {
            choices = new HashSet<choice>();
            exams_questions = new HashSet<exams_question>();
        }

        public int q_ID { get; set; }
        public string q_desc { get; set; }
        public string q_type { get; set; }
        public int c_ID { get; set; }

        public virtual course c_IDNavigation { get; set; }
        public virtual ICollection<choice> choices { get; set; }
        public virtual ICollection<exams_question> exams_questions { get; set; }
    }
}