// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination.Models
{
    public partial class student
    {
        public student()
        {
            exams = new HashSet<exam>();
            courses = new HashSet<course>();
        }

        public int stud_ID { get; set; }
        public string stud_Fname { get; set; }
        public string stud_Lname { get; set; }
        public int? dept_ID { get; set; }
        public string stud_Username { get; set; }
        public string stud_pw { get; set; }

        public virtual department dept { get; set; }
        public virtual ICollection<exam> exams { get; set; }

        public virtual ICollection<course> courses { get; set; }
    }
}