// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class students_selectResult
    {
        public int stud_ID { get; set; }
        public string stud_Fname { get; set; }
        public string stud_Lname { get; set; }
        public int? dept_ID { get; set; }
        public string stud_Username { get; set; }
        public string stud_pw { get; set; }
    }
}
