// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination.Models
{
    public partial class topic_selectResult
    {
        public int topic_ID { get; set; }
        public string topic_name { get; set; }
        public int course_ID { get; set; }
    }
}
